name: Manual Trigger Workflow with loglevel & tags

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Tags for the run'
        required: true
        default: 'example_tag'
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: echo "Purpose: ${{ github.event.inputs.tags }}"
